package vn.greenglobal.tttp.enums;

public enum CoQuanDieuTraThanhTraEnum {

	VIEN_KIEM_SAT("Viện kiểm sát"),
	
	TOA_AN_NHAN_DAN_TOI_CAO("Tòa án nhân dân tối cao"),
	TOA_AN_NHAN_DAN_CAP_CAP("Tóa án nhân dân cấp cao"),
	TOA_AN_NHAN_DAN_CAP_THANH_PHO("Tòa án nhân dân cấp thành phố"),
	TOA_AN_NHAN_DAN_HUYEN_HOA_VANG("Tòa án nhân dân huyện Hòa Vang"),
	TOA_AN_NHAN_DAN_HUYEN_HOANG_SA("Tòa án nhân dân huyện Hoàng Sa"),
	TOA_AN_NHAN_DAN_QUAN_CAM_LE("Tòa án nhân dân quận Cẩm Lệ"),
	TOA_AN_NHAN_DAN_QUAN_HAI_CHAU("Tòa án nhân dân quận Hải Châu"),
	TOA_AN_NHAN_DAN_QUAN_LIEN_CHIEU("Tòa án nhân dân quận Liên Chiểu"),
	TOA_AN_NHAN_DAN_QUAN_NGU_HANH_SON("Tòa án nhân dân quận Ngũ Hành Sơn"),
	TOA_AN_NHAN_DAN_QUAN_SON_TRA("Tòa án nhân dân quận Sơn Trà"),
	TOA_AN_NHAN_DAN_QUAN_THANH_KHE("Tòa án nhân dân quận Thanh Khê"),
	
	CONG_AN_THANH_PHO("Công an thành phố"),
	CONG_AN_QUAN_CAM_LE("Công an quận Cẩm Lệ"),
	CONG_AN_QUAN_HAI_CHAU("Công an quận Hải Châu"),
	CONG_AN_QUAN_LIEN_CHIEU("Công an quận Liên Chiểu"),
	CONG_AN_QUAN_NGU_HANH_SON("Công an quận Ngũ Hành Sơn"),
	CONG_AN_QUAN_SON_TRA("Công an quận Sơn Trà"),
	CONG_AN_QUAN_THANH_KHE("Công an quận Thanh Khê"),
	CONG_AN_HUYEN_HOA_VANG("Công an huyện Hòa Vang"),
	CONG_AN_HUYEN_HOANG_SA("Công an huyện Hoàng Sa"),
	CONG_AN_PHUONG_HOA_AN("Công an phường Hòa An"),
	CONG_AN_PHUONG_HOA_PHAT("Công an phường Hòa Phát"),
	CONG_AN_PHUONG_HOA_THO_DONG("Công an phường Hòa Thọ Đông"),
	CONG_AN_PHUONG_HOA_THO_TAY("Công an phường Hòa Thọ Tây"),
	CONG_AN_PHUONG_HOA_XUAN("Công an phường Hòa Xuân"),
	CONG_AN_PHUONG_KHUE_TRUNG("Công an phường Khuê Trung"),
	CONG_AN_PHUONG_BINH_HIEN("Công an phường Bình Hiên"),
	CONG_AN_PHUONG_BINH_THUAN("Công an phường Bình Thuận"),
	CONG_AN_PHUONG_HAI_CHAU_I("Công an phường Hải Châu I"),
	CONG_AN_PHUONG_HAI_CHAU_II("Công an phường Hải Châu II"),
	CONG_AN_PHUONG_HOA_CUONG_BAC("Công an phường Hòa Cường Bắc"),
	CONG_AN_PHUONG_HOA_CUONG_NAM("Công an phường Hòa Cường Nam"),
	CONG_AN_PHUONG_HOA_THUAN_DONG("Công an phường Hòa Thuận Đông"),
	CONG_AN_PHUONG_HOA_THUAN_TAY("Công an phường Hòa Thuận Tây"),
	CONG_AN_PHUONG_NAM_DUONG("Công an phường Nam Dương"),
	CONG_AN_PHUONG_PHUOC_NINH("Công an phường Phước Ninh"),
	CONG_AN_PHUONG_THACH_THANG("Công an phường Thạch Thang"),
	CONG_AN_PHUONG_THANH_BINH("Công an phường Thanh Bình"),
	CONG_AN_PHUONG_THUAN_PHUOC("Công an phường Thuận Phước"),
	CONG_AN_PHUONG_HOA_HIEP_BAC("Công an phường Hòa Hiệp Bắc"),
	CONG_AN_PHUONG_HOA_HIEP_NAM("Công an phường Hòa Hiệp Nam"),
	CONG_AN_PHUONG_HOA_KHANH_BAC("Công an phường Hòa Khánh Bắc"),
	CONG_AN_PHUONG_HOA_KHANH_NAM("Công an phường Hòa Khánh Nam"),
	CONG_AN_PHUONG_HOA_MINH("Công an phường Hòa Minh"),
	CONG_AN_PHUONG_HOA_HAI("Công an phường Hòa Hải"),
	CONG_AN_PHUONG_HOA_QUY("Công an phường Hòa Quý"),
	CONG_AN_PHUONG_KHUE_MY("Công an phường Khuê Mỹ"),
	CONG_AN_PHUONG_MY_AN("Công an phường Mỹ An"),
	CONG_AN_PHUONG_AN_HAI_BAC("Công an phường An Hải Bắc"),
	CONG_AN_PHUONG_AN_HAI_DONG("Công an phường An Hải Đông"),
	CONG_AN_PHUONG_AN_HAI_TAY("Công an phường An Hải Tây"),
	CONG_AN_PHUONG_MAN_THAI("Công an phường Mân Thái"),
	CONG_AN_PHUONG_NAI_HIEN_DONG("Công an phường Nại Hiên Đông"),
	CONG_AN_PHUONG_PHUOC_MY("Công an phường Phước Mỹ"),
	CONG_AN_PHUONG_THO_QUAN("Công an phường Thọ Quan"),
	CONG_AN_PHUONG_AN_KHE("Công an phường An Khê"),
	CONG_AN_PHUONG_CHINH_GIAN("Công an phường Chính Gián"),
	CONG_AN_PHUONG_HOA_KHUE("Công an phường Hòa Khuê"),
	CONG_AN_PHUONG_TAM_THUAN("Công an phường Tam Thuận"),
	CONG_AN_PHUONG_TAN_CHINH("Công an phường Tân Chính"),
	CONG_AN_PHUONG_THAC_GIAN("Công an phường Thạc Gián"),
	CONG_AN_PHUONG_THANH_KHE_DONG("Công an phường Thanh Khê Đông"),
	CONG_AN_PHUONG_THANH_KHE_TAY("Công an phường Thanh Khê Tây"),
	CONG_AN_PHUONG_VINH_TRUNG("Công an phường Vĩnh Trung"),
	CONG_AN_PHUONG_XUAN_HA("Công an phường Xuân Hà"),

	CO_QUAN_THI_HANH_THANH_PHO("Cơ quan thi hành án thành phố"),
	CO_QUAN_THI_HANH_QUAN_CAM_LE("Cơ quan thi hành án quận Cẩm Lệ"),
	CO_QUAN_THI_HANH_QUAN_HAI_CHAU("Cơ quan thi hành án quận Hải Châu"),
	CO_QUAN_THI_HANH_QUAN_LIEN_CHIEU("Cơ quan thi hành án quận Liên Chiểu"),
	CO_QUAN_THI_HANH_QUAN_NGU_HANH_SON("Cơ quan thi hành án quận Ngũ Hành Sơn"),
	CO_QUAN_THI_HANH_QUAN_SON_TRA("Cơ quan thi hành án quận Sơn Trà"),
	CO_QUAN_THI_HANH_QUAN_THANH_KHE("Cơ quan thi hành án quận Thanh Khê"),
	CO_QUAN_THI_HANH_HUYEN_HOA_VANG("Cơ quan thi hành án huyện Hòa Vang"),
	CO_QUAN_THI_HANH_HUYEN_HOANG_SA("Cơ quan thi hành án huyện Hoàng Sa"),
	CO_QUAN_THI_HANH_PHUONG_HOA_AN("Cơ quan thi hành án phường Hòa An"),
	CO_QUAN_THI_HANH_PHUONG_HOA_PHAT("Cơ quan thi hành án phường Hòa Phát"),
	CO_QUAN_THI_HANH_PHUONG_HOA_THO_DONG("Cơ quan thi hành án phường Hòa Thọ Đông"),
	CO_QUAN_THI_HANH_PHUONG_HOA_THO_TAY("Cơ quan thi hành án phường Hòa Thọ Tây"),
	CO_QUAN_THI_HANH_PHUONG_HOA_XUAN("Cơ quan thi hành án phường Hòa Xuân"),
	CO_QUAN_THI_HANH_PHUONG_KHUE_TRUNG("Cơ quan thi hành án phường Khuê Trung"),
	CO_QUAN_THI_HANH_PHUONG_BINH_HIEN("Cơ quan thi hành án phường Bình Hiên"),
	CO_QUAN_THI_HANH_PHUONG_BINH_THUAN("Cơ quan thi hành án phường Bình Thuận"),
	CO_QUAN_THI_HANH_PHUONG_HAI_CHAU_I("Cơ quan thi hành án phường Hải Châu I"),
	CO_QUAN_THI_HANH_PHUONG_HAI_CHAU_II("Cơ quan thi hành án phường Hải Châu II"),
	CO_QUAN_THI_HANH_PHUONG_HOA_CUONG_BAC("Cơ quan thi hành án phường Hòa Cường Bắc"),
	CO_QUAN_THI_HANH_PHUONG_HOA_CUONG_NAM("Cơ quan thi hành án phường Hòa Cường Nam"),
	CO_QUAN_THI_HANH_PHUONG_HOA_THUAN_DONG("Cơ quan thi hành án phường Hòa Thuận Đông"),
	CO_QUAN_THI_HANH_PHUONG_HOA_THUAN_TAY("Cơ quan thi hành án phường Hòa Thuận Tây"),
	CO_QUAN_THI_HANH_PHUONG_NAM_DUONG("Cơ quan thi hành án phường Nam Dương"),
	CO_QUAN_THI_HANH_PHUONG_PHUOC_NINH("Cơ quan thi hành án phường Phước Ninh"),
	CO_QUAN_THI_HANH_PHUONG_THACH_THANG("Cơ quan thi hành án phường Thạch Thang"),
	CO_QUAN_THI_HANH_PHUONG_THANH_BINH("Cơ quan thi hành án phường Thanh Bình"),
	CO_QUAN_THI_HANH_PHUONG_THUAN_PHUOC("Cơ quan thi hành án phường Thuận Phước"),
	CO_QUAN_THI_HANH_PHUONG_HOA_HIEP_BAC("Cơ quan thi hành án phường Hòa Hiệp Bắc"),
	CO_QUAN_THI_HANH_PHUONG_HOA_HIEP_NAM("Cơ quan thi hành án phường Hòa Hiệp Nam"),
	CO_QUAN_THI_HANH_PHUONG_HOA_KHANH_BAC("Cơ quan thi hành án phường Hòa Khánh Bắc"),
	CO_QUAN_THI_HANH_PHUONG_HOA_KHANH_NAM("Cơ quan thi hành án phường Hòa Khánh Nam"),
	CO_QUAN_THI_HANH_PHUONG_HOA_MINH("Cơ quan thi hành án phường Hòa Minh"),
	CO_QUAN_THI_HANH_PHUONG_HOA_HAI("Cơ quan thi hành án phường Hòa Hải"),
	CO_QUAN_THI_HANH_PHUONG_HOA_QUY("Cơ quan thi hành án phường Hòa Quý"),
	CO_QUAN_THI_HANH_PHUONG_KHUE_MY("Cơ quan thi hành án phường Khuê Mỹ"),
	CO_QUAN_THI_HANH_PHUONG_MY_AN("Cơ quan thi hành án phường Mỹ An"),
	CO_QUAN_THI_HANH_PHUONG_AN_HAI_BAC("Cơ quan thi hành án phường An Hải Bắc"),
	CO_QUAN_THI_HANH_PHUONG_AN_HAI_DONG("Cơ quan thi hành án phường An Hải Đông"),
	CO_QUAN_THI_HANH_PHUONG_AN_HAI_TAY("Cơ quan thi hành án phường An Hải Tây"),
	CO_QUAN_THI_HANH_PHUONG_MAN_THAI("Cơ quan thi hành án phường Mân Thái"),
	CO_QUAN_THI_HANH_PHUONG_NAI_HIEN_DONG("Cơ quan thi hành án phường Nại Hiên Đông"),
	CO_QUAN_THI_HANH_PHUONG_PHUOC_MY("Cơ quan thi hành án phường Phước Mỹ"),
	CO_QUAN_THI_HANH_PHUONG_THO_QUAN("Cơ quan thi hành án phường Thọ Quan"),
	CO_QUAN_THI_HANH_PHUONG_AN_KHE("Cơ quan thi hành án phường An Khê"),
	CO_QUAN_THI_HANH_PHUONG_CHINH_GIAN("Cơ quan thi hành án phường Chính Gián"),
	CO_QUAN_THI_HANH_PHUONG_HOA_KHUE("Cơ quan thi hành án phường Hòa Khuê"),
	CO_QUAN_THI_HANH_PHUONG_TAM_THUAN("Cơ quan thi hành án phường Tam Thuận"),
	CO_QUAN_THI_HANH_PHUONG_TAN_CHINH("Cơ quan thi hành án phường Tân Chính"),
	CO_QUAN_THI_HANH_PHUONG_THAC_GIAN("Cơ quan thi hành án phường Thạc Gián"),
	CO_QUAN_THI_HANH_PHUONG_THANH_KHE_DONG("Cơ quan thi hành án phường Thanh Khê Đông"),
	CO_QUAN_THI_HANH_PHUONG_THANH_KHE_TAY("Cơ quan thi hành án phường Thanh Khê Tây"),
	CO_QUAN_THI_HANH_PHUONG_VINH_TRUNG("Cơ quan thi hành án phường Vĩnh Trung"),
	CO_QUAN_THI_HANH_PHUONG_XUAN_HA("Cơ quan thi hành án phường Xuân Hà"),
	
	KHAC("Khác");
	
	CoQuanDieuTraThanhTraEnum(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}

	private String text;
}
